patient_database:
  target: dev
  outputs:
    dev:
      type: postgres
      host: postgres
      user: Itumeleng
      password: libra
      port: 5432
      dbname: patient_database
      schema: public
      threads: 1
