version: '3.8'
services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: Itumeleng
      POSTGRES_PASSWORD: libra
      POSTGRES_DB: patient_database
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U Itumeleng -d patient_database"]
      interval: 5s
      timeout: 5s
      retries: 5

  airflow-init:
    image: apache/airflow:2.11.0
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://Itumeleng:libra@postgres:5432/patient_database
      AIRFLOW__CORE__FERNET_KEY: "81HqDtbqAywKSOumSHA3BhWNOdQ26slT6K0YaZeZyPs="
      AIRFLOW__WEBSERVER__SECRET_KEY: "a25mQ1FHTUh3MnFRSk5KMEIyVVU2YmN0VGRyYTVXY08="
      AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
      _AIRFLOW_DB_MIGRATE: 'true'
      _AIRFLOW_WWW_USER_CREATE: 'true'
      _AIRFLOW_WWW_USER_USERNAME: Itumeleng
      _AIRFLOW_WWW_USER_PASSWORD: libra
      _AIRFLOW_WWW_USER_FIRSTNAME: Itumeleng
      _AIRFLOW_WWW_USER_LASTNAME: Mogase
      _AIRFLOW_WWW_USER_ROLE: Admin
      _AIRFLOW_WWW_USER_EMAIL: itumeleng@outlook.com
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./config:/opt/airflow/config
    user: "${AIRFLOW_UID:-50000}:0"
    command: version

  airflow-webserver:
    image: apache/airflow:2.11.0
    depends_on:
      airflow-init:
        condition: service_completed_successfully
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://Itumeleng:libra@postgres:5432/patient_database
      AIRFLOW__CORE__FERNET_KEY: "81HqDtbqAywKSOumSHA3BhWNOdQ26slT6K0YaZeZyPs="
      AIRFLOW__WEBSERVER__SECRET_KEY: "a25mQ1FHTUh3MnFRSk5KMEIyVVU2YmN0VGRyYTVXY08="
      AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    ports:
      - "8080:8080"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./config:/opt/airflow/config
    user: "${AIRFLOW_UID:-50000}:0"
    command: webserver
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    restart: unless-stopped

  airflow-scheduler:
    image: apache/airflow:2.11.0
    depends_on:
      airflow-init:
        condition: service_completed_successfully
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://Itumeleng:libra@postgres:5432/patient_database
      AIRFLOW__CORE__FERNET_KEY: "81HqDtbqAywKSOumSHA3BhWNOdQ26slT6K0YaZeZyPs="
      AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./config:/opt/airflow/config
    user: "${AIRFLOW_UID:-50000}:0"
    command: scheduler
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8974/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    restart: unless-stopped

  dbt:
    image: ghcr.io/dbt-labs/dbt-postgres:1.9.0
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./dbt:/dbt
    working_dir: /dbt
    environment:
      DBT_PROFILES_DIR: /dbt
    entrypoint: ["tail", "-f", "/dev/null"]

volumes:
  pgdata: